# Generated by Django 4.1.1 on 2023-11-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/')),
                ('image_name', models.CharField(max_length=255)),
                ('isSelect', models.BooleanField(default=False)),
                ('isFeatured', models.BooleanField(default=False)),
            ],
        ),
    ]
