# Generated by Django 4.1.1 on 2022-09-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='isCheckd',
            new_name='isChecked',
        ),
    ]
